/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.java.macro;

public class MAddElement {

    private final String pListName;

    private final String pElementName;

    private final MAddElement mAddElement = this;

    MAddElement(
            String pListName,
            String pElementName) {

        if (pListName == null) {
            throw new NullPointerException();
        }
        this.pListName = pListName;
        if (pElementName == null) {
            throw new NullPointerException();
        }
        this.pElementName = pElementName;
    }

    String pListName() {

        return this.pListName;
    }

    String pElementName() {

        return this.pElementName;
    }

    private String rListName() {

        return this.mAddElement.pListName();
    }

    private String rElementName() {

        return this.mAddElement.pElementName();
    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append(rListName());
        sb.append(".add(");
        sb.append(rElementName());
        sb.append(");");
        sb.append(System.getProperty("line.separator"));
        return sb.toString();
    }

}
