/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.java.macro;

import java.util.*;

public class MNewParameter {

    private final String pTreeAlternative;

    private final MNewParameter mNewParameter = this;

    private final List<Object> eNormalParameter_NewParameter_EndParameter = new LinkedList<Object>();

    MNewParameter(
            String pTreeAlternative) {

        if (pTreeAlternative == null) {
            throw new NullPointerException();
        }
        this.pTreeAlternative = pTreeAlternative;
    }

    public MNormalParameter newNormalParameter(
            String pElementType,
            String pElementName,
            String pIndex) {

        MNormalParameter lNormalParameter = new MNormalParameter(pElementType,
                pElementName, pIndex);
        this.eNormalParameter_NewParameter_EndParameter.add(lNormalParameter);
        return lNormalParameter;
    }

    public MNewParameter newNewParameter(
            String pTreeAlternative) {

        MNewParameter lNewParameter = new MNewParameter(pTreeAlternative);
        this.eNormalParameter_NewParameter_EndParameter.add(lNewParameter);
        return lNewParameter;
    }

    public MEndParameter newEndParameter() {

        MEndParameter lEndParameter = new MEndParameter();
        this.eNormalParameter_NewParameter_EndParameter.add(lEndParameter);
        return lEndParameter;
    }

    String pTreeAlternative() {

        return this.pTreeAlternative;
    }

    private String rTreeAlternative() {

        return this.mNewParameter.pTreeAlternative();
    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("new N");
        sb.append(rTreeAlternative());
        sb.append("(-1, -1");
        if (this.eNormalParameter_NewParameter_EndParameter.size() > 0) {
            sb.append(", ");
        }
        {
            boolean first = true;
            for (Object oNormalParameter_NewParameter_EndParameter : this.eNormalParameter_NewParameter_EndParameter) {
                if (first) {
                    first = false;
                }
                else {
                    sb.append(", ");
                }
                sb.append(oNormalParameter_NewParameter_EndParameter.toString());
            }
        }
        sb.append(")");
        return sb.toString();
    }

}
