/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.java.macro;

import java.util.*;

public class MNewTreeClass {

    private final String pElementType;

    private final String pElementName;

    private final MNewTreeClass mNewTreeClass = this;

    private final List<Object> eNormalParameter_NullParameter_NewParameter_EndParameter = new LinkedList<Object>();

    MNewTreeClass(
            String pElementType,
            String pElementName) {

        if (pElementType == null) {
            throw new NullPointerException();
        }
        this.pElementType = pElementType;
        if (pElementName == null) {
            throw new NullPointerException();
        }
        this.pElementName = pElementName;
    }

    public MNormalParameter newNormalParameter(
            String pElementType,
            String pElementName,
            String pIndex) {

        MNormalParameter lNormalParameter = new MNormalParameter(pElementType,
                pElementName, pIndex);
        this.eNormalParameter_NullParameter_NewParameter_EndParameter
                .add(lNormalParameter);
        return lNormalParameter;
    }

    public MNullParameter newNullParameter() {

        MNullParameter lNullParameter = new MNullParameter();
        this.eNormalParameter_NullParameter_NewParameter_EndParameter
                .add(lNullParameter);
        return lNullParameter;
    }

    public MNewParameter newNewParameter(
            String pElementName) {

        MNewParameter lNewParameter = new MNewParameter(pElementName);
        this.eNormalParameter_NullParameter_NewParameter_EndParameter
                .add(lNewParameter);
        return lNewParameter;
    }

    public MEndParameter newEndParameter() {

        MEndParameter lEndParameter = new MEndParameter();
        this.eNormalParameter_NullParameter_NewParameter_EndParameter
                .add(lEndParameter);
        return lEndParameter;
    }

    String pElementType() {

        return this.pElementType;
    }

    String pElementName() {

        return this.pElementName;
    }

    private String rElementType() {

        return this.mNewTreeClass.pElementType();
    }

    private String rElementName() {

        return this.mNewTreeClass.pElementName();
    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("      new N");
        sb.append(rElementType());
        sb.append(" n");
        sb.append(rElementName());
        sb.append(" = new N");
        sb.append(rElementType());
        sb.append(" (-1, -1");
        if (this.eNormalParameter_NullParameter_NewParameter_EndParameter
                .size() > 0) {
            sb.append(", ");
        }
        {
            boolean first = true;
            for (Object oNormalParameter_NullParameter_NewParameter_EndParameter : this.eNormalParameter_NullParameter_NewParameter_EndParameter) {
                if (first) {
                    first = false;
                }
                else {
                    sb.append(", ");
                }
                sb.append(oNormalParameter_NullParameter_NewParameter_EndParameter
                        .toString());
            }
        }
        sb.append(");");
        sb.append(System.getProperty("line.separator"));
        return sb.toString();
    }

}
