/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.java.macro;

import java.util.*;

public class MNodeList {

    private final List<Object> eDefaultPackage_SpecifiedPackage = new LinkedList<Object>();

    public MNodeList() {

    }

    public MDefaultPackage newDefaultPackage(
            String pLanguageName) {

        MDefaultPackage lDefaultPackage = new MDefaultPackage(pLanguageName);
        this.eDefaultPackage_SpecifiedPackage.add(lDefaultPackage);
        return lDefaultPackage;
    }

    public MSpecifiedPackage newSpecifiedPackage(
            String pLanguageName,
            String pPackage) {

        MSpecifiedPackage lSpecifiedPackage = new MSpecifiedPackage(
                pLanguageName, pPackage);
        this.eDefaultPackage_SpecifiedPackage.add(lSpecifiedPackage);
        return lSpecifiedPackage;
    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append(new MHeader().toString());
        if (this.eDefaultPackage_SpecifiedPackage.size() > 0) {
            sb.append(System.getProperty("line.separator"));
        }
        for (Object oDefaultPackage_SpecifiedPackage : this.eDefaultPackage_SpecifiedPackage) {
            sb.append(oDefaultPackage_SpecifiedPackage.toString());
        }
        sb.append(System.getProperty("line.separator"));
        sb.append("public class NodeList<TNode extends Node> extends Node{");
        sb.append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));
        sb.append("	private ArrayList<TNode> elements;");
        sb.append(System.getProperty("line.separator"));
        sb.append("	");
        sb.append(System.getProperty("line.separator"));
        sb.append("	private int lowerBound;");
        sb.append(System.getProperty("line.separator"));
        sb.append("	private int upperBound;");
        sb.append(System.getProperty("line.separator"));
        sb.append("	");
        sb.append(System.getProperty("line.separator"));
        sb.append("	private const in INF = -1;");
        sb.append(System.getProperty("line.separator"));
        sb.append("	");
        sb.append(System.getProperty("line.separator"));
        sb.append("	NodeList(ArrayList<Node> elements,int lowerBound){");
        sb.append(System.getProperty("line.separator"));
        sb.append("		");
        sb.append(System.getProperty("line.separator"));
        sb.append("		this.elements = elements;");
        sb.append(System.getProperty("line.separator"));
        sb.append("		this.lowerBound = lowerBound;");
        sb.append(System.getProperty("line.separator"));
        sb.append("		this.upperBound = INF;");
        sb.append(System.getProperty("line.separator"));
        sb.append("	}");
        sb.append(System.getProperty("line.separator"));
        sb.append("	");
        sb.append(System.getProperty("line.separator"));
        sb.append("	NodeList(ArrayList<Node> elements, int lowerBound,upperBound){");
        sb.append(System.getProperty("line.separator"));
        sb.append("		this.elements = elements;");
        sb.append(System.getProperty("line.separator"));
        sb.append("		this.lowerBound = lowerBound;");
        sb.append(System.getProperty("line.separator"));
        sb.append("		this.upperBound = upperBound;");
        sb.append(System.getProperty("line.separator"));
        sb.append("	}");
        sb.append(System.getProperty("line.separator"));
        sb.append("	");
        sb.append(System.getProperty("line.separator"));
        sb.append("	add(TNode element){");
        sb.append(System.getProperty("line.separator"));
        sb.append("		this.elements.add(element);");
        sb.append(System.getProperty("line.separator"));
        sb.append("	}");
        sb.append(System.getProperty("line.separator"));
        sb.append("	");
        sb.append(System.getProperty("line.separator"));
        sb.append("	addList(NodeList elements){");
        sb.append(System.getProperty("line.separator"));
        sb.append("		this.elements.addAll(elements);");
        sb.append(System.getProperty("line.separator"));
        sb.append("	}");
        sb.append(System.getProperty("line.separator"));
        sb.append("	");
        sb.append(System.getProperty("line.separator"));
        sb.append("	List<Nodes> getNodes(){");
        sb.append(System.getProperty("line.separator"));
        sb.append("		return this.elements;");
        sb.append(System.getProperty("line.separator"));
        sb.append("	}");
        sb.append(System.getProperty("line.separator"));
        sb.append("	");
        sb.append(System.getProperty("line.separator"));
        sb.append("	");
        sb.append(System.getProperty("line.separator"));
        sb.append("}");
        sb.append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));
        return sb.toString();
    }

}
