/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.java.macro;

import java.util.*;

public class MPublicElementAccessor {

    private final String pElementName;

    private final MPublicElementAccessor mPublicElementAccessor = this;

    private final List<Object> ePublicElementType_PublicListElementType_TokenElementType = new LinkedList<Object>();

    MPublicElementAccessor(
            String pElementName) {

        if (pElementName == null) {
            throw new NullPointerException();
        }
        this.pElementName = pElementName;
    }

    public MPublicElementType newPublicElementType(
            String pElementType) {

        MPublicElementType lPublicElementType = new MPublicElementType(
                pElementType);
        this.ePublicElementType_PublicListElementType_TokenElementType
                .add(lPublicElementType);
        return lPublicElementType;
    }

    public MPublicListElementType newPublicListElementType(
            String pElementType) {

        MPublicListElementType lPublicListElementType = new MPublicListElementType(
                pElementType);
        this.ePublicElementType_PublicListElementType_TokenElementType
                .add(lPublicListElementType);
        return lPublicListElementType;
    }

    public MTokenElementType newTokenElementType() {

        MTokenElementType lTokenElementType = new MTokenElementType();
        this.ePublicElementType_PublicListElementType_TokenElementType
                .add(lTokenElementType);
        return lTokenElementType;
    }

    String pElementName() {

        return this.pElementName;
    }

    private String rElementName() {

        return this.mPublicElementAccessor.pElementName();
    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("  public ");
        for (Object oPublicElementType_PublicListElementType_TokenElementType : this.ePublicElementType_PublicListElementType_TokenElementType) {
            sb.append(oPublicElementType_PublicListElementType_TokenElementType
                    .toString());
        }
        sb.append(" get_");
        sb.append(rElementName());
        sb.append("() {");
        sb.append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));
        sb.append("    return this.e");
        sb.append(rElementName());
        sb.append(";");
        sb.append(System.getProperty("line.separator"));
        sb.append("  }");
        sb.append(System.getProperty("line.separator"));
        return sb.toString();
    }

}
