/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.java.macro;

import java.util.*;

public class MReduce {

    private final String pReducedProduction;

    private final MReduce mReduce = this;

    private final List<Object> eReduceNormalPop_ReduceEndPop = new LinkedList<Object>();

    private final List<Object> eReduceDecision = new LinkedList<Object>();

    private final List<Object> eNormalParameter = new LinkedList<Object>();

    private final List<Object> eNewParameter = new LinkedList<Object>();

    private final List<Object> eNullParameter = new LinkedList<Object>();

    private final List<Object> eEndParameter = new LinkedList<Object>();

    private final List<Object> eAddElement = new LinkedList<Object>();

    private final List<Object> eAddList = new LinkedList<Object>();

    private final List<Object> eAcceptDecision = new LinkedList<Object>();

    MReduce(
            String pReducedProduction) {

        if (pReducedProduction == null) {
            throw new NullPointerException();
        }
        this.pReducedProduction = pReducedProduction;
    }

    public MReduceDecision newReduceDecision() {

        MReduceDecision lReduceDecision = new MReduceDecision(this.mReduce);
        this.eReduceDecision.add(lReduceDecision);
        return lReduceDecision;
    }

    public MNormalParameter newNormalParameter(
            String pElementType,
            String pElementName,
            String pIndex) {

        MNormalParameter lNormalParameter = new MNormalParameter(pElementType,
                pElementName, pIndex);
        this.eNormalParameter.add(lNormalParameter);
        return lNormalParameter;
    }

    public MNewParameter newNewParameter(
            String pElementName) {

        MNewParameter lNewParameter = new MNewParameter(pElementName);
        this.eNewParameter.add(lNewParameter);
        return lNewParameter;
    }

    public MNullParameter newNullParameter() {

        MNullParameter lNullParameter = new MNullParameter();
        this.eNullParameter.add(lNullParameter);
        return lNullParameter;
    }

    public MEndParameter newEndParameter() {

        MEndParameter lEndParameter = new MEndParameter();
        this.eEndParameter.add(lEndParameter);
        return lEndParameter;
    }

    public MAddElement newAddElement(
            String pListName,
            String pElementName) {

        MAddElement lAddElement = new MAddElement(pListName, pElementName);
        this.eAddElement.add(lAddElement);
        return lAddElement;
    }

    public MAddList newAddList(
            String pListName,
            String pElementName) {

        MAddList lAddList = new MAddList(pListName, pElementName);
        this.eAddList.add(lAddList);
        return lAddList;
    }

    public MAcceptDecision newAcceptDecision(
            String pElementName) {

        MAcceptDecision lAcceptDecision = new MAcceptDecision(pElementName);
        this.eAcceptDecision.add(lAcceptDecision);
        return lAcceptDecision;
    }

    public MReduceNormalPop newReduceNormalPop(
            String pElementName) {

        MReduceNormalPop lReduceNormalPop = new MReduceNormalPop(pElementName);
        this.eReduceNormalPop_ReduceEndPop.add(lReduceNormalPop);
        return lReduceNormalPop;
    }

    public MReduceEndPop newReduceEndPop() {

        MReduceEndPop lReduceEndPop = new MReduceEndPop();
        this.eReduceNormalPop_ReduceEndPop.add(lReduceEndPop);
        return lReduceEndPop;
    }

    String pReducedProduction() {

        return this.pReducedProduction;
    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("      ParseStack stack = parser.getStack();");
        sb.append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));
        for (Object oReduceNormalPop_ReduceEndPop : this.eReduceNormalPop_ReduceEndPop) {
            sb.append(oReduceNormalPop_ReduceEndPop.toString());
        }
        sb.append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));
        for (Object oReduceDecision : this.eReduceDecision) {
            sb.append(oReduceDecision.toString());
        }
        sb.append(System.getProperty("line.separator"));
        for (Object oNormalParameter : this.eNormalParameter) {
            sb.append(oNormalParameter.toString());
        }
        sb.append(System.getProperty("line.separator"));
        for (Object oNewParameter : this.eNewParameter) {
            sb.append(oNewParameter.toString());
        }
        sb.append(System.getProperty("line.separator"));
        for (Object oNullParameter : this.eNullParameter) {
            sb.append(oNullParameter.toString());
        }
        sb.append(System.getProperty("line.separator"));
        for (Object oEndParameter : this.eEndParameter) {
            sb.append(oEndParameter.toString());
        }
        sb.append(System.getProperty("line.separator"));
        for (Object oAddElement : this.eAddElement) {
            sb.append(oAddElement.toString());
        }
        sb.append(System.getProperty("line.separator"));
        for (Object oAddList : this.eAddList) {
            sb.append(oAddList.toString());
        }
        sb.append(System.getProperty("line.separator"));
        for (Object oAcceptDecision : this.eAcceptDecision) {
            sb.append(oAcceptDecision.toString());
        }
        return sb.toString();
    }

}
