/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.java.macro;

import java.util.*;

public class MReduceDecision {

    private final MReduce mReduce;

    private final List<Object> eReduceNewElement = new LinkedList<Object>();

    private final List<Object> eReduceUpElement = new LinkedList<Object>();

    private final List<Object> eReduceListElement = new LinkedList<Object>();

    MReduceDecision(
            MReduce mReduce) {

        if (mReduce == null) {
            throw new NullPointerException();
        }
        this.mReduce = mReduce;
    }

    public MReduceNewElement newReduceNewElement(
            String pTreeAlternative) {

        MReduceNewElement lReduceNewElement = new MReduceNewElement(
                pTreeAlternative);
        this.eReduceNewElement.add(lReduceNewElement);
        return lReduceNewElement;
    }

    public MReduceUpElement newReduceUpElement(
            String pElementName,
            String pIndex) {

        MReduceUpElement lReduceUpElement = new MReduceUpElement(pElementName,
                pIndex);
        this.eReduceUpElement.add(lReduceUpElement);
        return lReduceUpElement;
    }

    public MReduceListElement newReduceListElement() {

        MReduceListElement lReduceListElement = new MReduceListElement();
        this.eReduceListElement.add(lReduceListElement);
        return lReduceListElement;
    }

    private String rReducedProduction() {

        return this.mReduce.pReducedProduction();
    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("      List<Node> trees = new LinkedList<Node>();");
        sb.append(System.getProperty("line.separator"));
        for (Object oReduceNewElement : this.eReduceNewElement) {
            sb.append(oReduceNewElement.toString());
        }
        for (Object oReduceUpElement : this.eReduceUpElement) {
            sb.append(oReduceUpElement.toString());
        }
        for (Object oReduceListElement : this.eReduceListElement) {
            sb.append(oReduceListElement.toString());
        }
        sb.append("      stack.push(new AbstractForest(CSTProductionType.P_");
        sb.append(rReducedProduction());
        sb.append(",trees, stack.getState().getTarget(CSTProductionType.P_");
        sb.append(rReducedProduction());
        sb.append("));");
        sb.append(System.getProperty("line.separator"));
        return sb.toString();
    }

}
