/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.java.macro;

public class MReduceListElement {

    MReduceListElement() {

    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("	  // ???");
        sb.append(System.getProperty("line.separator"));
        return sb.toString();
    }

}
